{
 "title": "Network Availability",
 "tags": [
  "blackbox",
  "smokeping",
  "smokeping-kit",
  "status"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "ICMP Status History",
   "type": "status-history",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "min by (address) ((2 * (avg_over_time(probe_success{probe=~\"icmp|icmp_ipv6\", address!~\"127.0.0.1\"}[$__interval]) == bool 1)) + ((avg_over_time(probe_success{probe=~\"icmp|icmp_ipv6\", address!~\"127.0.0.1\"}[$__interval]) > bool 0) * (avg_over_time(probe_success{probe=~\"icmp|icmp_ipv6\", address!~\"127.0.0.1\"}[$__interval]) < bool 1)))",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "HTTP Status History",
   "type": "status-history",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "min by (address) ((2 * (avg_over_time(probe_success{probe=~\"http_head_200|http_head_200_ipv6|http_get_body|http_get_body_ipv6|https_cert|https_cert_ipv6\"}[$__interval]) == bool 1)) + ((avg_over_time(probe_success{probe=~\"http_head_200|http_head_200_ipv6|http_get_body|http_get_body_ipv6|https_cert|https_cert_ipv6\"}[$__interval]) > bool 0) * (avg_over_time(probe_success{probe=~\"http_head_200|http_head_200_ipv6|http_get_body|http_get_body_ipv6|https_cert|https_cert_ipv6\"}[$__interval]) < bool 1)))",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "TCP Status History",
   "type": "status-history",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "min by (address) ((2 * (avg_over_time(probe_success{probe=~\"tcp_connect|tcp_connect_ipv6|tcp_tls|tcp_tls_ipv6\"}[$__interval]) == bool 1)) + ((avg_over_time(probe_success{probe=~\"tcp_connect|tcp_connect_ipv6|tcp_tls|tcp_tls_ipv6\"}[$__interval]) > bool 0) * (avg_over_time(probe_success{probe=~\"tcp_connect|tcp_connect_ipv6|tcp_tls|tcp_tls_ipv6\"}[$__interval]) < bool 1)))",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "DNS Status History",
   "type": "status-history",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "min by (address) ((2 * (avg_over_time(probe_success{probe=~\"dns_udp_a|dns_udp_aaaa\"}[$__interval]) == bool 1)) + ((avg_over_time(probe_success{probe=~\"dns_udp_a|dns_udp_aaaa\"}[$__interval]) > bool 0) * (avg_over_time(probe_success{probe=~\"dns_udp_a|dns_udp_aaaa\"}[$__interval]) < bool 1)))",
     "legendFormat": "{{address}}"
    }
   ]
  }
 ]
}