{
 "title": "Network Latency",
 "tags": [
  "blackbox",
  "smokeping",
  "smokeping-kit"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "ICMP Prober (IPv4)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_icmp_duration_seconds{phase=\"rtt\", probe=\"icmp\", address!~\"127.0.0.1\"} and on (job, instance) probe_success{probe=\"icmp\", address!~\"127.0.0.1\"} == 1",
     "legendFormat": "{{address}}"
    },
    {
     "expr": "avg(probe_icmp_duration_seconds{phase=\"rtt\", probe=\"icmp\", address!~\"127.0.0.1\"} and on (job, instance) probe_success{probe=\"icmp\", address!~\"127.0.0.1\"} == 1)",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "ICMP Prober (IPv6)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_icmp_duration_seconds{phase=\"rtt\", probe=\"icmp_ipv6\"} and on (job, instance) probe_success{probe=\"icmp_ipv6\"} == 1",
     "legendFormat": "{{address}}"
    },
    {
     "expr": "avg(probe_icmp_duration_seconds{phase=\"rtt\", probe=\"icmp_ipv6\"} and on (job, instance) probe_success{probe=\"icmp_ipv6\"} == 1)",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "HTTP Prober (IPv4)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_duration_seconds{probe=~\"http_head_200|http_get_body|https_cert\"} and on (job, instance) probe_success{probe=~\"http_head_200|http_get_body|https_cert\"} == 1",
     "legendFormat": "{{address}}"
    },
    {
     "expr": "avg(probe_duration_seconds{probe=~\"http_head_200|http_get_body|https_cert\"} and on (job, instance) probe_success{probe=~\"http_head_200|http_get_body|https_cert\"} == 1)",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "HTTP Prober (IPv6)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_duration_seconds{probe=~\"http_head_200_ipv6|http_get_body_ipv6|https_cert_ipv6\"} and on (job, instance) probe_success{probe=~\"http_head_200_ipv6|http_get_body_ipv6|https_cert_ipv6\"} == 1",
     "legendFormat": "{{address}}"
    },
    {
     "expr": "avg(probe_duration_seconds{probe=~\"http_head_200_ipv6|http_get_body_ipv6|https_cert_ipv6\"} and on (job, instance) probe_success{probe=~\"http_head_200_ipv6|http_get_body_ipv6|https_cert_ipv6\"} == 1)",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "TCP Prober (IPv4)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_duration_seconds{probe=~\"tcp_connect|tcp_tls\"} and on (job, instance) probe_success{probe=~\"tcp_connect|tcp_tls\"} == 1",
     "legendFormat": "{{address}}"
    },
    {
     "expr": "avg(probe_duration_seconds{probe=~\"tcp_connect|tcp_tls\"} and on (job, instance) probe_success{probe=~\"tcp_connect|tcp_tls\"} == 1)",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "TCP Prober (IPv6)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_duration_seconds{probe=~\"tcp_connect_ipv6|tcp_tls_ipv6\"} and on (job, instance) probe_success{probe=~\"tcp_connect_ipv6|tcp_tls_ipv6\"} == 1",
     "legendFormat": "{{address}}"
    },
    {
     "expr": "avg(probe_duration_seconds{probe=~\"tcp_connect_ipv6|tcp_tls_ipv6\"} and on (job, instance) probe_success{probe=~\"tcp_connect_ipv6|tcp_tls_ipv6\"} == 1)",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "DNS Prober (A)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_dns_duration_seconds{probe=\"dns_udp_a\", phase=\"request\"} and on (job, instance) probe_success{probe=\"dns_udp_a\"} == 1",
     "legendFormat": "{{address}}"
    },
    {
     "expr": "avg(probe_dns_duration_seconds{probe=\"dns_udp_a\", phase=\"request\"} and on (job, instance) probe_success{probe=\"dns_udp_a\"} == 1)",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "DNS Prober (AAAA)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_dns_duration_seconds{probe=\"dns_udp_aaaa\", phase=\"request\"} and on (job, instance) probe_success{probe=\"dns_udp_aaaa\"} == 1",
     "legendFormat": "{{address}}"
    },
    {
     "expr": "avg(probe_dns_duration_seconds{probe=\"dns_udp_aaaa\", phase=\"request\"} and on (job, instance) probe_success{probe=\"dns_udp_aaaa\"} == 1)",
     "legendFormat": "Average"
    }
   ]
  }
 ]
}